version: '3.3'
services:
    app:
        build:
            context: ./dockerfiles
        container_name: kairos
        restart: always
        user: "root"
        env_file:
            - ../../.env
        volumes:
            - "../../:/var/www/project:cached"
            - "~/.composer:/root/.composer"
        networks:
            - dev
        working_dir: /var/www/project
        labels:
            - "traefik.backend=${PROJECT_NAME}.apache2"
            - "traefik.frontend.rule=Host:${PROJECT_NAME}.${DOMAIN_NAME}.${DOMAIN_EXTENSION}"
            - "traefik.port=8000"

networks:
    dev:
        external:
            name: wowdockerenv_dev
